-- CONSTRAINT PRIMARY KEY
ALTER TABLE OGRENCI ADD (
         CONSTRAINT PK_OGRENCI_ID PRIMARY KEY (OgrenciID)
);

ALTER TABLE OGRETMEN ADD (
         CONSTRAINT PK_OGRETMEN_ID PRIMARY KEY (OgretmenID)
);

ALTER TABLE YONETICI ADD (
         CONSTRAINT PK_YONETICI_ID PRIMARY KEY (YoneticiID)
);

ALTER TABLE LOGIN ADD (
         CONSTRAINT PK_LOGIN_ID PRIMARY KEY (LogID)
);

ALTER TABLE VELI ADD (
         CONSTRAINT PK_VELI_ID PRIMARY KEY (VeliID)
);
ALTER TABLE MAAS ADD (
         CONSTRAINT PK_MAAS_ID PRIMARY KEY (MaasID)
);
ALTER TABLE ODEME ADD (
         CONSTRAINT PK_ODEME_ID PRIMARY KEY (OdemeID)
);

ALTER TABLE DEVAMSIZLIK ADD (
         CONSTRAINT PK_DEVAMSIZLIK_ID PRIMARY KEY (DevamsizlikID)
);
ALTER TABLE GRUP ADD (
         CONSTRAINT PK_GRUP_ID PRIMARY KEY (GrupID)
         
);
ALTER TABLE SINIF ADD (
         CONSTRAINT PK_SINIF_ID PRIMARY KEY (SinifID)
         
);
ALTER TABLE DERSLER ADD (
         CONSTRAINT PK_DERS_ID PRIMARY KEY (DersID)
         
);

ALTER TABLE BRANS ADD (
         CONSTRAINT PK_BRANS_ID PRIMARY KEY (BransID)
         
);
ALTER TABLE DENEME ADD (
         CONSTRAINT PK_DENEME_ID PRIMARY KEY (DenemeID)
         
);
ALTER TABLE SONUC ADD (
         CONSTRAINT PK_SONUC_ID PRIMARY KEY (SonucID)
         
);
commit;

-- CONSTRAINT FOREIGN KEY
ALTER TABLE OGRENCI ADD (
         CONSTRAINT FK_VELiID FOREIGN KEY (VeliID) REFERENCES VELI (VeliID)
         ,CONSTRAINT FK_SINIF_ID FOREIGN KEY (SinifID) REFERENCES SINIF (SinifID)
);

ALTER TABLE OGRETMEN ADD (
         CONSTRAINT FK_BRANS_ID FOREIGN KEY (BransID) REFERENCES BRANS (BransID)
         ,CONSTRAINT FK_MAAS_ID FOREIGN KEY (MaasID) REFERENCES MAAS (MaasID)
);

ALTER TABLE LOGIN ADD (
         CONSTRAINT FK_YONETICI_ID FOREIGN KEY (YoneticiID) REFERENCES YONETICI (YoneticiID)
);

ALTER TABLE ODEME ADD (
            CONSTRAINT FK_OGRENCI_ID FOREIGN KEY (OgrenciID) REFERENCES OGRENCI (OgrenciID)
);

ALTER TABLE DEVAMSIZLIK ADD (
            CONSTRAINT FK_OGRENCIID FOREIGN KEY (OgrenciID) REFERENCES OGRENCI (OgrenciID)
);
ALTER TABLE DERSLER ADD (
         CONSTRAINT FK_OGRETMEN_ID FOREIGN KEY (OgretmenID) REFERENCES OGRETMEN (OgretmenID)
         ,CONSTRAINT FK_SINIFID FOREIGN KEY (SinifID) REFERENCES SINIF (SinifID)
);
ALTER TABLE SINIF ADD (
            CONSTRAINT FK_GRUP_ID FOREIGN KEY (GrupID) REFERENCES GRUP (GrupID)
);
ALTER TABLE SONUC ADD ( 
      CONSTRAINT FK_OgrenciiID FOREIGN KEY (OgrenciID) REFERENCES OGRENCI (OgrenciID)
         ,CONSTRAINT FK_DENEME_ID FOREIGN KEY (DenemeID) REFERENCES DENEME (DenemeID)
 
);


